fox_stats_name_matching = {'Matthew|Murray': 'Matt|Murray',
                           'MacKenzie|Blackwood': 'Mackenzie|Blackwood',
                           'Jakob|Forsbacka Karlsson': 'Jakob|Karlsson',
                           'Max|Veronneau': 'Max|V\xc3\xa9ronneau',
                           'James|van Riemsdyk': 'James|Riemsdyk',
                           'Louis|Belpedio': 'Louie|Belpedio',
                           'TJ|Brodie': 'T.J.|Brodie',
                           'Michael|Del Zotto': 'Michael|Zotto',
                           'J-F|Berube': 'Jean-Francois|Berube',
                           "Daniel|O'Regan": "Danny|O'Regan",
                           "Vincent|Hinostroza": "Vinnie|Hinostroza",
                           "William|Borgen": "Will|Borgen",
                           "Cameron|Johnson": "Cam|Johnson",
                           "Joshua|Morrissey": "Josh|Morrissey",
                           "Phillip|Di Giuseppe": "Phillip|Giuseppe",
                           "Quintin|Hughes": "Quinn|Hughes",
                           "Timothy|Gettinger": "Tim|Gettinger",
                           "Theodor|Blueger": "Teddy|Blueger",
                           "Steven|Santini": "Steve|Santini",
                           "Benjamin|Gleason": "Ben|Gleason",
                           "Alex|Debrincat": "Alex|DeBrincat",
                           "Joseph|Gambardella": "Joe|Gambardella",
                           "Nick|Paul": "Nicholas|Paul",
                           "Alexander|Petrovic": "Alex|Petrovic",
                           "Joshua|Ho-Sang": "Josh|Ho-Sang",
                           "Michael|Dal Colle": "Michael|Colle",
                           "Matt|Dumba": "Mathew|Dumba",
                           "Joshua|Mahura": "Josh|Mahura",
                           "Calvin|De Haan": "Calvin|Haan",
                           "Trevor|van Riemsdyk": "Trevor|Riemsdyk",
                           "Mike|Matheson": "Michael|Matheson",
                           "Phil|Varone": "Philip|Varone",
                           "Tony|DeAngelo": "Anthony|DeAngelo",
                           "MacKenzie|MacEachern": "Mackenzie|MacEachern",
                           "Joel|Eriksson Ek": "Joel|Ek",
                           "Maxime|Lajoie": "Max|Lajoie",
                           "Matt|Puempel": "Matthew|Puempel"
                           }

nhl_stats_name_matching = {
    "Danny|O'Regan": "Daniel|O'Regan",
    "Jacob|de la Rose": "Jacob|De La Rose",
    "Boo|Nieves": "Cristoval|Nieves",
    "Pat|Maroon": "Patrick|Maroon",
    "Josh|Mahura": "Joshua|Mahura",
    "Louie|Belpedio": "Louis|Belpedio",
    "Quinn|Hughes": "Quintin|Hughes",
    "Zach|Werenski": "Zachary|Werenski",
    "Tim|Gettinger": "Timothy|Gettinger",
    "Teddy|Blueger": "Theodor|Blueger",
    "Ryan|Nugent-Hopkins": "Ryan|Nugent-Hopkinzs",
    "Vinnie|Hinostroza": "Vincent|Hinostroza",
    "Josh|Morrissey": "Joshua|Morrissey",
    "Josh|Brown": "Joshua|Brown",
    "Calvin|de Haan": "Calvin|De Haan",
    "Max|Comtois": "Maxime|Comtois",
    "Alex|DeBrincat": "Alex|Debrincat",
    "Ben|Gleason": "Benjamin|Gleason",
    "Mackenzie|MacEachern": "MacKenzie|MacEachern",
    "Zach|Aston-Reese": "Zachary|Aston-Reese",
}

team_matching = {'LAK': 'LA', 'SJS': 'SJ', 'NJD': 'NJ', 'TBL': 'TB'}
