Learn:
  keep_prob : 0.9
  learning_rate : 0.0001
  number_of_total_game: 1130
  batch_size: 32
  max_seq_length: 10
  save_mother_dir: "/Local-Scratch"
  feature_type: "V1"
  iterate_num: 30
  model_type: 'normal'
  number_of_total_game: 1202
  action_number : 33
  gamma : 1
  data_name: 'ice_hockey-2019'
  sport : 'Ice-Hockey'
  predict_target : 'PlayerLocalId'
  player_Id_style: 'PlayerId'
  position_max_length : 15
  apply_stochastic: True
  apply_box_score: False
  diff_apply_rl: True
  apply_pid: False
  integral_update_flag: True
  rnn_skip_player: False
  decoder_skip_condition: True
  embed_mode : 'random'

Arch:
  CVRNN:
    hidden_dim : 512
    latent_dim : 256
    x_dim : 150 # playerId dimension
    y_dim : 71 # 12state+27action+31team+1reward
  SARSA:
    lstm_layer_num : 2
    h_size : 256
    dense_layer_number : 2
    dense_layer_size : 256
  WIN:
    lstm_layer_num : 2
    h_size : 256
    dense_layer_number : 2
    dense_layer_size : 256
  Predict:
    lstm_layer_num : 2
    h_size : 256
    dense_layer_number : 2
    dense_layer_size : 256
    output_size : 2
    predict_target: 'ActionGoal'